### PR TITLE
make gen_qsub_script give crop a full absolute parent_dir

### PR DESCRIPTION
**Pull request by adamcallison**

### CODE REVIEW

**Comment by adamcallison** [comment]
Simplest patch I could think of for making `qsub_grow` work if the `Crop`'s `parent_dir` is a relative path. Alternative approach would be to modify `parse_crop_details` to find the absolute path so that `Crop`s always have absolute paths. Thoughts?

**Comment by jcmgray** [comment]
This looks like it makes sense. Is it necessary to take the ``cd {working_directory}`` out? I'm only thinking that maybe the output of the job will no longer be in the ``working_directory`` as expected.

**Comment by adamcallison** [comment]
> This looks like it makes sense. Is it necessary to take the `cd {working_directory}` out? I'm only thinking that maybe the output of the job will no longer be in the `working_directory` as expected.

I took it out because I don't think it was doing anything - I'm not sure how things work with SGE but on PBS the output files go to where qsub was called. Perhaps the right thing to do is to inherit the working directory from the python process that calls gen_qsub_script, rather than go the `crop.parent_dir` so that relative paths in the user's actual function get appropriately respected?

**Comment by jcmgray** [comment]
I think best to leave the ``cd`` in, if the function creates log or temporary files or whatever then probably best to have them output in the crop parents directory.

The best policy for dealing with relative paths might be to call ``os.path.abspath(os.path.expanduser(my_path))``, where necessary. What do you think? I definitely haven't thought about the use cases/implementation in a while though...

**Comment by jcmgray** [comment]
Or I think ``pathlib`` is the python 3+ recommended way of doing things these days.

**Comment by adamcallison** [comment]
Ok, I put the `cd` back in and switched to pathlib (I hadn't heard of pathlib before - it does seem like a better way)

**Comment by jcmgray** [comment]
Nice, in the absence of being able to do tests - have you tried it on cx1 with a ``Crop`` in a different place / relative parent folder?

**Comment by adamcallison** [comment]
Yes, just did a simple test case. It works.

**Comment by jcmgray** [comment]
Amazing, thanks very much again!

**Pull request merged**
